#!C:/Program\ Files/Git/usr/bin/sh.exe

COMMIT_FILE=$1
COMMIT_MSG=$(cat $1)
STAGED_FILES=$(git diff --name-only --cached)

RELEASE_COMMIT_MSG_PATTERN="^prepare \d{4}\.\d{2}\.\d{2}$"

if [[ $COMMIT_MSG == prepare* ]]; then
  if [[ ! $COMMIT_MSG =~ $RELEASE_COMMIT_MSG_PATTERN ]]; then
    echo "Error: invalid release commit message pattern: 'prepare xxxx.xx.xx'"
    exit 1
  fi

  echo "[release] $COMMIT_MSG" > $COMMIT_FILE
  exit 0
fi

for file in $STAGED_FILES; do

  # check is manual editing
  if [[ $file == "MANUAL.md" ]] || [[ $file == Resources/Manual/* ]]; then
    echo "[manual] $COMMIT_MSG" > $COMMIT_FILE
    exit 0
  fi

  if [[ $file == Example/* ]]; then
    echo "[example] $COMMIT_MSG" > $COMMIT_FILE
    exit 0
  fi

  if [[ $file == VSRAD.Syntax/* ]]; then
    echo "[syntax] $COMMIT_MSG" > $COMMIT_FILE
    exit 0
  fi

done

